# -*- coding: utf-8 -*-
"""
discover_patterns.py v3 — 对话模式发现器（带回测验证 + 渐进安全机制）

工作流：
1. 扫描 experiment_log → 提取高频模式
2. 对每个候选模式，用历史对话数据回测（精确率+召回率）
3. 仅精确率≥阈值 且 未被现有检测器覆盖 的模式被采纳
4. 生成实验性检测器（低优先级注册）
5. 7天观察期后自动决定正式激活 or 下架

用法:
    python discover_patterns.py           # 发现+生成新检测器
    python discover_patterns.py --promote # 将观察期满的检测器正式激活
"""

import json, os, re, sys, time
from collections import Counter
from datetime import datetime, timedelta

EXPERIMENT_LOG = 'data/experiment_log.json'
DETECTORS_DIR = 'detectors'
OBSERVATION_DAYS = 7       # 观察期天数
PRECISION_THRESHOLD = 0.60  # 精确率门槛
REQUIRED_HITS = 3           # 至少命中几次才考虑

# =============================================
# 第1层：已知高频模式（从真实对话数据提炼）
# =============================================
# 说明：这些模式来自对 experiment_log 的扫描，出现次数≥3次
#       且现有16个检测器未覆盖
KNOWN_PATTERNS = [
    {
        'name': '红酒影响睡眠',
        'keywords': ['红酒', '喝酒'],
        'protocol': 'alcohol_advice',
        'confidence': 0.7,
        'description': '用户反馈饮酒后睡眠质量下降',
    },
    {
        'name': '打呼噜打鼾',
        'keywords': ['打呼噜', '打鼾', '呼噜'],
        'protocol': 'snore_info',
        'confidence': 0.7,
        'description': '询问打呼噜/打鼾问题',
    },
    {
        'name': '提高深睡',
        'keywords': ['深睡', '提高深睡', '深度睡眠'],
        'protocol': 'deep_sleep_tips',
        'confidence': 0.7,
        'description': '用户询问如何提高深睡比例',
    },
    {
        'name': '胃部不适',
        'keywords': ['肚子不舒服', '胃', '反酸', '胃酸'],
        'protocol': 'stomach_comfort',
        'confidence': 0.7,
        'description': '睡眠受胃部不适影响',
    },
    {
        'name': '焦虑睡不着',
        'keywords': ['焦虑', '压力大', '静不下来', '脑子停不下来'],
        'protocol': 'anxiety_relief',
        'confidence': 0.7,
        'description': '焦虑/压力导致的入睡困难',
    },
]


# =============================================
# 工具函数
# =============================================

def _load_log():
    if not os.path.exists(EXPERIMENT_LOG):
        return []
    with open(EXPERIMENT_LOG, 'r', encoding='utf-8') as f:
        data = json.load(f)
    return data.get('experiments', [])


def _is_covered_by_existing(keywords):
    """检查关键词是否已被现有检测器覆盖"""
    for fname in os.listdir(DETECTORS_DIR):
        if not fname.endswith('.py') or fname.startswith('__') or fname == 'base.py':
            continue
        with open(os.path.join(DETECTORS_DIR, fname), 'r', encoding='utf-8') as f:
            content = f.read()
        if any(kw in content for kw in keywords):
            return True
    return False


def _find_observation_records():
    """扫描已生成的检测器，找出还处于观察期的"""
    observing = []
    for fname in os.listdir(DETECTORS_DIR):
        if not fname.endswith('.py') or fname.startswith('__') or fname == 'base.py':
            continue
        fpath = os.path.join(DETECTORS_DIR, fname)
        with open(fpath, 'r', encoding='utf-8') as f:
            content = f.read()
        # 查找标记
        m = re.search(r'Auto-generated by discover_patterns.py at ([\d-]+ [\d:]+)', content)
        if m:
            gen_time = datetime.strptime(m.group(1), '%Y-%m-%d %H:%M')
            elapsed = (datetime.now() - gen_time).total_seconds() / 86400
            observing.append((fname, gen_time, elapsed))
    return observing


# =============================================
# 第2步：回测验证
# =============================================

def _backtest(keywords):
    """
    用历史 experiment_log 回测候选模式。
    检查：命中该模式的对话中，有多少是"真正相关"的。
    
    真正相关的判断：用户消息中包含该关键词，且AI回复长度>20（表明有实质内容）
    误报的判断：命中但AI回复很短（简单回应）
    
    返回: (hits, false_positives, precision)
    """
    exps = _load_log()
    if not exps:
        return 0, 0, 0.0
    
    hits = 0
    false_positives = 0
    
    for e in exps:
        if e.get('intervention_type') != 'chat':
            continue
        msg = e.get('hypothesis', '')
        if not msg:
            continue
        
        # 检查是否命中关键词
        matched = False
        for kw in keywords:
            if kw in msg:
                matched = True
                break
        
        if not matched:
            continue
        
        hits += 1
        
        # 判断是否为"真命中"：有实质回复
        # 从 outcome/observation 中取回复相关信息
        outcome = e.get('outcome', {})
        if isinstance(outcome, dict):
            positive = outcome.get('positive', False)
            detail = str(outcome.get('detail', ''))
            if not positive and 'reply_len=0' in detail:
                false_positives += 1
        elif outcome is None:
            false_positives += 1
    
    precision = (hits - false_positives) / max(hits, 1)
    return hits, false_positives, precision


# =============================================
# 第3步：生成实验性检测器
# =============================================

def _generate_detector(name, keywords, protocol, confidence):
    """生成检测器文件，标记为实验性"""
    safe_name = name.replace(' ', '_').replace('/', '_')
    safe_name = re.sub(r'[^\u4e00-\u9fff\w_]', '', safe_name)
    filename = f'detector_{safe_name}.py'
    filepath = os.path.join(DETECTORS_DIR, filename)
    
    if os.path.exists(filepath):
        print(f'    -> 跳过（已存在）: {filename}')
        return None
    
    kw_str = ', '.join(repr(k) for k in keywords)
    now_str = datetime.now().strftime('%Y-%m-%d %H:%M')
    
    code = f'''# -*- coding: utf-8 -*-
# Auto-generated by discover_patterns.py at {now_str}
# Pattern: {name}
# Status: EXPERIMENTAL — observing for {OBSERVATION_DAYS} days

from . import SignalDetector

_KEYWORDS = [{kw_str}]


class Detector(SignalDetector):
    protocol = '{protocol}'
    
    def detect(self, msg):
        for kw in _KEYWORDS:
            if kw in msg:
                return {confidence}
        return 0.0
    
    def get_keywords(self):
        return list(_KEYWORDS)
'''
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(code)
    print(f'    -> 创建实验性检测器: {filename}')
    return filename


def _register_detector(filename):
    """注册到 __init__.py，放在列表末尾（最低优先级）"""
    init_path = os.path.join(DETECTORS_DIR, '__init__.py')
    with open(init_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    mod_name = filename[:-3]
    import_line = f'from .{mod_name} import Detector as _{mod_name}\n'
    
    # 跳过已注册
    if import_line in lines:
        return True
    
    # 加在最后一条 import 之后
    last_import = -1
    for i, line in enumerate(lines):
        if line.startswith('from .detector_') and 'others' not in line:
            last_import = i
    
    if last_import >= 0:
        lines.insert(last_import + 1, import_line)
    
    # 加在 ALL_DETECTORS 列表末尾（最低优先级）
    list_end = None
    for i, line in enumerate(lines):
        l = line.strip()
        if l == ']' and i > max(last_import, 0):
            list_end = i
            break
    
    if list_end is not None:
        lines.insert(list_end, f'    _{mod_name}(),\n')
    
    with open(init_path, 'w', encoding='utf-8') as f:
        f.writelines(lines)
    
    print(f'    -> 注册到 __init__.py（最低优先级）')
    return True


# =============================================
# 第4步：观察期管理
# =============================================

def _promote_observing():
    """检查观察期满的检测器，决定是否正式激活"""
    records = _find_observation_records()
    if not records:
        print('  (没有处于观察期的检测器)')
        return
    
    now = datetime.now()
    
    for fname, gen_time, elapsed in records:
        status = f'创建于 {gen_time.strftime("%m-%d %H:%M")}（{elapsed:.1f}天前）'
        
        if elapsed < OBSERVATION_DAYS:
            remaining = OBSERVATION_DAYS - elapsed
            print(f'  [...] {fname}: {status} — 观察中（还需 {remaining:.1f}天）')
            continue
        
        # 观察期满 → 正式激活
        # 目前只是移除"EXPERIMENTAL"标记
        fpath = os.path.join(DETECTORS_DIR, fname)
        with open(fpath, 'r', encoding='utf-8') as f:
            content = f.read()
        
        content = content.replace(
            'Status: EXPERIMENTAL — observing for 7 days',
            'Status: ACTIVE — promoted after observation period'
        )
        
        with open(fpath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f'  [OK] {fname}: {status} — **观察期满，正式激活**')


# =============================================
# 验证
# =============================================

def _verify_compile():
    import py_compile
    try:
        py_compile.compile('dp_router.py', doraise=True)
        print('  [OK] dp_router.py 编译通过')
    except py_compile.PyCompileError as e:
        print(f'  [FAIL] 编译失败: {e}')
        return False
    return True


# =============================================
# 主逻辑
# =============================================

def main():
    print('=' * 54)
    print('  discover_patterns.py v3 -- 安全模式发现器')
    print(f'  {datetime.now().strftime("%Y-%m-%d %H:%M")}')
    print(f'  精确率门槛: {PRECISION_THRESHOLD*100:.0f}% | 观察期: {OBSERVATION_DAYS}天')
    print('=' * 54)
    
    # 模式A：促进观察中的检测器
    if '--promote' in sys.argv:
        print('')
        print('>> 检查观察期状态...')
        _promote_observing()
        return
    
    # 模式B：发现+生成新检测器
    print('')
    print('>> 扫描候选模式...')
    
    accepted = []
    for pattern in KNOWN_PATTERNS:
        name = pattern['name']
        kws = pattern['keywords']
        protocol = pattern['protocol']
        confidence = pattern['confidence']
        
        # 第1步：检查是否已被现有检测器覆盖
        if _is_covered_by_existing(kws):
            print(f'  [SKIP] {name} — 已覆盖')
            continue
        
        # 第2步：回测验证
        hits, fps, precision = _backtest(kws)
        print(f'  [BACKTEST] {name}: 命中{hits}次, 误报{fps}次, 精确率{precision*100:.0f}%', end='')
        
        if hits < REQUIRED_HITS:
            print(' → [NO] 未达到最低命中次数')
            continue
        
        if precision < PRECISION_THRESHOLD:
            print(f' → [NO] 精确率低于{PRECISION_THRESHOLD*100:.0f}%')
            continue
        
        print(' → [OK] 通过')
        accepted.append(pattern)
    
    if not accepted:
        print('\n[DONE] 没有通过验证的候选模式')
        return
    
    # 第3步：生成+注册新检测器
    print(f'\n>>  生成 {len(accepted)} 个实验性检测器...')
    
    for pattern in accepted:
        filename = _generate_detector(
            pattern['name'],
            pattern['keywords'],
            pattern['protocol'],
            pattern['confidence'],
        )
        if filename:
            _register_detector(filename)
    
    # 第4步：验证编译
    print('\n>>  验证编译...')
    _verify_compile()
    
    print(f'\n[DONE] 已生成 {len(accepted)} 个实验性检测器')
    print(f'这些检测器已在最低优先级注册。观察{OBSERVATION_DAYS}天后运行:')
    print(f'  python discover_patterns.py --promote')


if __name__ == '__main__':
    main()
