route:
  group_by: ['alert_group']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
  - match:
      severity: 'page'
    receiver: 'pagerduty'
  - match:
      severity: 'critical'
    receiver: 'slack'
  - match_re:
      severity: 'warning|info'
    receiver: 'email'
